### PR TITLE
Allow building with transformers 0.5 (on GHC 8 RC)

### PR DESCRIPTION
**Pull request by Heather**

### CODE REVIEW

**Comment by glguy** [comment]
This PR breaks the build on GHC 7.6 and earlier. Do you happen to know what the dependency conflict is? (It was hidden in the build output due to a redirect)

**Comment by RyanGlScott** [comment]
I believe the build is broken for a spurious reason: the `.travis.yml` script we're using caches its installed dependencies, and checks if there's been updated packages by comparing the output of `cabal install --only-dependencies --dry-run` with its cache. Here is what I believe is happening:

* Versions of GHC prior to GHC 7.8 don't depend on `transformers`, so they try to install the latest version of `transformers` by default
* Unfortunately, a lof of `kan-extensions`' dependencies have upper version bounds of `transformers < 0.5` on Hackage, which causes an inconsistent buildplan. For whatever reason, this is confusing `cabal-install` enough that it quits and returns an error (unfortunately, we can't tell for sure due to the truncated build output)

I opted to merge this since it's morally harmless (although Travis might disagree, sadly). If you want, we can add GHC 7.4/7.6 to the allowed-to-fail section until @ekmett gets a chance to upload new versions of his packages to Hackage with the proper version bounds.

**Comment by RyanGlScott** [comment]
Another possibility is that there's a solver bug in `cabal-install-1.16` (as GHC 7.4 and 7.6 are the only ones using it in the `.travis.yml` config). My evidence for this claim is that I tried running the same command with `cabal-install-1.22`:

```
$ cabal install --only-dependencies --enable-tests --enable-benchmarks --dry --with-ghc /opt/ghc/7.6.3/bin/ghc
base-orphans-0.5.0
prelude-extras-0.4.0.2
stm-2.4.4.1
tagged-0.8.2
text-1.2.2.0
hashable-1.2.4.0
nats-1.1
transformers-0.4.3.0 (latest: 0.5.0.0)
StateVar-1.1.0.2
mtl-2.2.1
transformers-compat-0.4.0.4
distributive-0.4.4
exceptions-0.8.1
unordered-containers-0.2.6.0
semigroups-0.18.0.1
bifunctors-5.1
void-0.7.1
contravariant-1.3.3
comonad-4.2.7.2
profunctors-5.1.2
semigroupoids-5.0.0.4
free-4.12.2
adjunctions-4.2.2
```

And it worked just fine. Perhaps this would be worth bumping `CABALVER` to at least 1.18 for all GHCs in `.travis.yml`.

**Comment by RyanGlScott** [comment]
Yep, it was a `cabal-install-1.16` bug... using `cabal-install-1.18` for the old GHCs [fixed](https://travis-ci.org/ekmett/kan-extensions/builds/102716955) it.

**Pull request merged**
